train:
  # experiment directory path
  exp_dir: "#TODO DiffBIR/exp_dir/exp_channel_vae01/"
  # stage 1 swinir path
  learning_rate: 8e-6
  warmup_steps: 500
  # ImageNet 1k (1.3M images)
  # batch size = 192, lr = 1e-4, total training steps = 25k
  # Our filtered laion2b-en (15M images)
  # batch size = 256, lr = 1e-4 (first 30k), 1e-5 (next 50k), total training steps = 80k
  batch_size: 2
  num_workers: 1
  train_steps: 10000
  learn_iter_num: 1
  log_every: 20
  ckpt_every: 500
  image_every: 100
  # resume: "#TODO DiffBIR/exp_dir/exp3/checkpoints/0015000.pt"
  # vae_resume: "#TODO DiffBIR/weights/raw_vae.pt"
  channel_vae_resume: "#TODO weights/model_vae_c14_bu2_k31_7_r_allca_k31_2024-06-06_loss0.000583.pt"
  vae_resume: #TODO DiffBIR/exp_dir/exp_vae02f01/checkpoints/0040000_vae.pt
